Fix for Issue 407: CRTF region parsing
astropy/regions pull request #408
Opened 2021-12-14 01:37 UTC by keflavich

CRTFs appear to interpret :'s as hour-separating, .'s as degree-separating.

2021-12-27 15:50 UTC, dhomeier requested changes
Looks OK apart from either fixing the failing test and/or setting a default unit.
Defaulting to `hms` for RA makes sense anyway, but it's a bit strange the format is not clearly defined. I think right now an input like
> 18:20:30.12 4:11:54.69
would parse declination as `hms` as well; should it raise an invalid format error instead or default to `dms` for declination?

2021-12-27 15:50 UTC, dhomeier commented on regions/io/crtf/read.py
> +            unit = u.hour
```suggestion
        unit = u.deg
        if len(string_rep.split('.')) >= 3:
            string_rep = string_rep.replace('.', ':', 2)
        elif string_rep.count(":") == 2:
            unit = u.hour
```
Should there be a default `unit`, e.g. shall 10.119 be parsed as `10.119 * u.deg`?
Thought that was causing the test to fail, but actually it is just not raising the right exception now, expecting input like '18h12m24s' to raise `CRTFRegionParserError`, getting `undefined variable 'unit'` instead.

2021-12-30 13:05 UTC, dhomeier commented on regions/io/crtf/tests/test_crtf.py
> +    assert regs[0].center.ra == 281.93342096*u.deg
```suggestion
    assert_quantity_allclose(regs[0].center.ra, 281.93342096*u.deg, rtol=1e-9)
```
Looked a bit suspicious with the float comparison, but that was a nasty one lurking just past the default printed digits! Will need
`from astropy.tests.helper import assert_quantity_allclose`
at the top (though `np.allclose` should work now with quantities for all supported numpy versions as well).

2022-07-19 00:47 UTC, dmehring commented
In the hope that this will help clarify CRTF.

Angular measures of the form 05h30m22s represent  angular measures using time syntax, in hours, minutes, seconds eg, RA. Angular measures of the form 5d30m22s represent angles in degrees, arcmin, arcsec. The leading "h" or "d" determines the type.

From a previous comment:

"18:20:30.12 4:11:54.69"

In CRTF format, if the second measure is intended to represent a declination in the usual degrees,arcmin,arcsec, it should be written as 4.11.54.89. The first form (with : delimiters) represents angular measures using time syntax, the second represents angles in degrees.arcmin.arcsec.fraction_of_arcsec

2022-10-26 17:48 UTC, larrybradley approved these changes
Thanks, @keflavich!

2022-10-26 17:48 UTC, merged